server:
  port:

spring:
  profiles:
    include: secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

jwt:
  secret:
    access:
    refresh:
  time:
    access:
    refresh:

logging:
  slack:
    webhook-uri:
  config: